apiVersion: v2
name: ingress-nginx
version: 1.0.0
description: A Helm chart for Kubernetes
dependencies:
  - name: ingress-nginx
    version: 4.8.0
    repository: https://kubernetes.github.io/ingress-nginx
