apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devteam-a
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Enable DevTeam-A Project to install new applications

  sourceRepos:
    - "*"

  destinations:
    - namespace: "devteam-a"
      server: https://kubernetes.default.svc

  clusterResourceBlacklist:
    - group: ""
      kind: "Namespace"

  namespaceResourceBlacklist:
    - group: "argoproj.io"
      kind: "AppProject"
    - group: "argoproj.io"
      kind: "Application"
    - group: ""
      kind: "ResourceQuota"
    - group: "networking.k8s.io"
      kind: "NetworkPolicy"
