apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-docker-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/savagame/GitOps-At-Scale-Multitenancy.git
    targetRevision: main
    path: ./infrastructure/docker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
